# Generated by Django 3.2.14 on 2025-07-07 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('last_location', models.CharField(blank=True, max_length=255)),
                ('created_location', models.CharField(blank=True, max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_managed', models.BooleanField(default=False)),
                ('is_password_expired', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_password_autoset', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('billing_address_country', models.CharField(default='INDIA', max_length=255)),
                ('billing_address', models.JSONField(null=True)),
                ('has_billing_address', models.BooleanField(default=False)),
                ('user_timezone', models.CharField(default='Asia/Kolkata', max_length=255)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('last_logout_time', models.DateTimeField(null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=255)),
                ('last_logout_ip', models.CharField(blank=True, max_length=255)),
                ('last_login_medium', models.CharField(default='email', max_length=20)),
                ('last_login_uagent', models.TextField(blank=True)),
                ('token_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
