# Generated by Django 3.2.14 on 2025-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20250707_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employer', 'Employer')], default='student', max_length=255),
        ),
    ]
